### Chuyển đổi file dữ liệu chỉ có nhãn CSI về định dạng chuẩn

In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv(r"total_23026_CSI_0.txt", sep = "\t", header=0)

In [6]:
df["title"] = np.nan
df["subject"] = np.nan
df["object"] = np.nan
df["sức mạnh"] = np.nan
df["thiết kế"] = np.nan
df["giá"] = np.nan
df["tính năng"]= np.nan
df["an toàn"] = np.nan

In [7]:
cols = list(df.columns.values)
print(cols)

['sentence_idx', 'sentence', 'CSI', 'title', 'subject', 'object', 'sức mạnh', 'thiết kế', 'giá', 'tính năng', 'an toàn']

In [8]:
cols = ['sentence_idx', 'title', 'sentence', 'CSI', 'subject', 'object', 'sức mạnh', 'thiết kế', 'giá', 'tính năng', 'an toàn']
df_ = df[cols]

In [9]:
df_['title'] =  df_['title'].fillna("none")

In [10]:
df_['CSI'] = df_['CSI'].apply(np.int64)

In [11]:
df_

,sentence_idx,title,sentence,CSI,subject,object,sức mạnh,thiết kế,giá,tính năng,an toàn
0,383,none,sau khi honda city rs 2021 chính_thức được trì...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,383,none,đó là thêm bộ bodykit,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,383,none,để tìm_hiểu rõ hơn về 2 phiên_bản thể_thao này...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,383,none,"ngoài 5 biến_thể đã bán từ trước , toyota đã b...",0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,383,none,"đặc_biệt , ở thế_hệ mới , honda còn cung_cấp đ...",0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
23021,117,none,honda civic type r có_thể hoàn_thành một vòng ...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23022,117,none,trong khi focus rs vẫn chưa xác_định được thời...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23023,117,none,honda civic type r mới sở_hữu hệ_thống giảm_ch...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23024,117,none,lần đầu_tiên honda civic được cung_cấp chế_độ ...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23025,117,none,theo carscoops,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df_ = df_.sample(n=1000)
df_.to_csv(r"./txt/1000_CSI_0_noAC_noNER_.txt", header=True, index = None, sep="\t", mode='w')

In [13]:
df_.to_excel("./xlsx/1000_CSI_0_noAC_noNER_.xlsx", index = None)

### Mix dữ liệu định dạng chuẩn CSI nhãn 0 và CSI nhãn 1 thành dữ liệu final

In [ ]:
df1 = pd.read_csv(r"./txt/611_CSI1_AC_NER.txt", sep = "\t", header=0)
df0 = pd.read_csv(r"./txt/1000_CSI0_noAC_noNER.txt", sep = "\t", header=0)

In [ ]:
print(df0.dtypes)

sentence_idx      int64
title            object
sentence         object
CSI               int64
subject         float64
object          float64
sức mạnh        float64
thiết kế        float64
giá             float64
tính năng       float64
an toàn         float64
dtype: object

In [ ]:
df = df1.append(df0, ignore_index=True)

C:\Users\Hieu Vu\AppData\Local\Temp\ipykernel_12324\2460284396.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df1.append(df0, ignore_index=True)

In [ ]:
df

,sentence_idx,title,sentence,CSI,subject,object,sức mạnh,thiết kế,giá,tính năng,an toàn
0,220,So sánh VinFast Lux SA2.0 2021 và Kia Sorento ...,điểm vượt_trội của sorento so với đối_thủ đến ...,1,4&&,7&&,0.0,0.0,0.0,0.0,3.0
1,220,So sánh VinFast Lux SA2.0 2021 và Kia Sorento ...,"trong khi đó , kia sorento 2021 là một chiếc x...",1,5&& 6&& 7&&,NaN,0.0,0.0,0.0,0.0,3.0
2,442,"So sánh xe MG ZS 2021 và Ford EcoSport 2021: ""...","trong khi đó , ford ecosport vẫn mang đến nhữn...",1,5&& 6&&,25&&,0.0,0.0,0.0,0.0,1.0
3,442,"So sánh xe MG ZS 2021 và Ford EcoSport 2021: ""...","đặc_biệt , chiếc xe này có những công_nghệ an_...",1,3&& 4&& 5&&,11&& 12&&,0.0,0.0,0.0,0.0,3.0
4,376,So sánh xe Honda CR-V 2020 và Subaru Forester ...,"nhờ đó , những chiếc xe subaru luôn được biết ...",1,7&&,15&&,0.0,0.0,0.0,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...
1606,477,none,"với mitsubishi attrage 2020 , thiết_kế thân xe...",0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1607,398,none,"hyundai elantra có tới 4 chế_độ lái , trong đó...",0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1608,238,none,"nếu bạn thích một tay_lái tinh_tế , “ thông_mi...",0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1609,181,none,một thay_đổi rất đáng chú_ý là hộp_số tự_động ...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1610,164,none,"đối_với phiên_bản range rover se và hse 2018 ,...",0,NaN,NaN,NaN,NaN,NaN,NaN,NaN